const localHost=/^(?:localhost|0\.0\.0\.0|127(?:\.\d{1,3}){3}|10(?:\.\d{1,3}){3}|192\.168(?:\.\d{1,3}){2}|172\.(?:1[6-9]|2\d|3[01])(?:\.\d{1,3}){2})$/i.test(location.hostname);const API=window.MPWR_API_URL||(localHost?`http://${location.hostname==="0.0.0.0"?"127.0.0.1":location.hostname}:3000/v1`:"/api/v1");
const $=s=>document.querySelector(s);let email="",token="",files=[],previewUrls=[];const message=$("#appeal-message");
function show(id,step){document.querySelectorAll(".appeal-step").forEach(el=>el.classList.toggle("active",el.id===id));document.querySelectorAll(".appeal-progress span").forEach((el,i)=>el.classList.toggle("active",i<step));message.textContent=""}
async function api(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(token?{"X-Appeal-Token":token}:{}),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Something went wrong. Please try again.");return data}
const initialEmail=new URLSearchParams(location.search).get("email")||"";$("#appeal-email").value=initialEmail;
const explanation=$("#appeal-explanation");function autosizeExplanation(){explanation.style.height="auto";explanation.style.height=`${Math.min(explanation.scrollHeight,180)}px`;explanation.style.overflowY=explanation.scrollHeight>180?"auto":"hidden"}explanation.addEventListener("input",autosizeExplanation);autosizeExplanation();
$("#appeal-email-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.currentTarget.querySelector("button");email=$("#appeal-email").value.trim();button.disabled=true;try{const result=await api("/account-appeals/request-code",{method:"POST",body:JSON.stringify({email})});$("#appeal-email-copy").textContent=email;$("#appeal-preview-code").hidden=!result.previewCode;$("#appeal-preview-code").textContent=result.previewCode?`Local preview code: ${result.previewCode}`:"";show("appeal-code-step",2)}catch(error){message.textContent=error.message}finally{button.disabled=false}});
$("#appeal-back").addEventListener("click",()=>show("appeal-email-step",1));
$("#appeal-code-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.currentTarget.querySelector("button");button.disabled=true;try{const result=await api("/account-appeals/verify",{method:"POST",body:JSON.stringify({email,code:$("#appeal-code").value.trim()})});token=result.token;$("#appeal-reason").textContent=result.account.reason;$("#appeal-blocked-date").textContent=`Restricted ${new Date(result.account.blockedAt).toLocaleDateString("en-UG",{day:"numeric",month:"short",year:"numeric"})}`;show("appeal-form-step",3)}catch(error){message.textContent=error.message}finally{button.disabled=false}});
function renderFiles(){previewUrls.forEach(URL.revokeObjectURL);previewUrls=[];const list=$("#appeal-files");list.replaceChildren();files.forEach((file,index)=>{const item=document.createElement("div");item.className="appeal-file";const image=document.createElement("img");const url=URL.createObjectURL(file);previewUrls.push(url);image.src=url;image.alt=`Supporting picture ${index+1}`;const remove=document.createElement("button");remove.type="button";remove.setAttribute("aria-label",`Remove ${file.name}`);remove.innerHTML='<img src="images/Icon Folder/Close Icon_333.PNG" alt="">';remove.addEventListener("click",()=>{files=files.filter((_file,fileIndex)=>fileIndex!==index);renderFiles()});item.append(image,remove);list.append(item)});$(".appeal-add-photo").classList.toggle("is-disabled",files.length>=3)}
$("#appeal-evidence").addEventListener("change",e=>{const selected=new Map(files.map(file=>[`${file.name}:${file.size}:${file.lastModified}`,file]));[...e.target.files].forEach(file=>selected.set(`${file.name}:${file.size}:${file.lastModified}`,file));files=[...selected.values()].slice(0,3);e.target.value="";renderFiles()});
$("#appeal-form").addEventListener("submit",async e=>{e.preventDefault();const button=e.currentTarget.querySelector("button");button.disabled=true;message.textContent=files.some(file=>file.size>5*1024*1024)?"Each image must be 5 MB or smaller.":"";if(message.textContent){button.disabled=false;return}try{const evidence=[];for(const file of files){const body=new FormData();body.append("file",file);evidence.push(await api("/account-appeals/evidence",{method:"POST",body}))}const result=await api("/account-appeals",{method:"POST",body:JSON.stringify({explanation:$("#appeal-explanation").value.trim(),evidence})});$("#appeal-reference").textContent=result.reference;show("appeal-success-step",3)}catch(error){message.textContent=error.message}finally{button.disabled=false}});
