CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE user_role AS ENUM ('customer','admin'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE shipping_class AS ENUM ('small','medium','large'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE order_status AS ENUM ('pending','processing','shipped','delivered','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_status AS ENUM ('pending','successful','failed','refunded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL UNIQUE,password_hash text NOT NULL,first_name text NOT NULL,last_name text NOT NULL,phone text,role user_role NOT NULL DEFAULT 'customer',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS addresses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,label text,address text NOT NULL,city text NOT NULL,district text NOT NULL,country text NOT NULL DEFAULT 'Uganda',google_place_id text,latitude numeric(10,7),longitude numeric(10,7),is_default boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS addresses_one_default_per_user ON addresses(user_id) WHERE is_default = true;
CREATE TABLE IF NOT EXISTS fulfillment_centers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,address text NOT NULL,latitude numeric(10,7) NOT NULL,longitude numeric(10,7) NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),legacy_id text UNIQUE,title text NOT NULL,slug text NOT NULL UNIQUE,description text,price integer NOT NULL CHECK(price>=0),currency text NOT NULL DEFAULT 'UGX',image_url text,shipping_class shipping_class NOT NULL DEFAULT 'small',weight_grams integer,active boolean NOT NULL DEFAULT true,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS product_variants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid NOT NULL REFERENCES products(id) ON DELETE CASCADE,sku text NOT NULL UNIQUE,name text NOT NULL,price integer,stock integer NOT NULL DEFAULT 0,options jsonb NOT NULL DEFAULT '{}',active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS delivery_rate_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),version text NOT NULL,min_km numeric(8,1) NOT NULL,max_km numeric(8,1),small_fee integer NOT NULL,medium_fee integer NOT NULL,large_fee integer NOT NULL,min_days integer NOT NULL,max_days integer NOT NULL,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(version,min_km));
CREATE UNIQUE INDEX IF NOT EXISTS delivery_rules_version_min_unique ON delivery_rate_rules(version,min_km);
CREATE TABLE IF NOT EXISTS delivery_quotes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id),fulfillment_center_id uuid NOT NULL REFERENCES fulfillment_centers(id),destination jsonb NOT NULL,distance_km numeric(8,1) NOT NULL,duration_minutes integer NOT NULL,shipping_class shipping_class NOT NULL,subtotal integer NOT NULL,fee integer NOT NULL,total integer NOT NULL,pricing_version text NOT NULL,expires_at timestamptz NOT NULL,consumed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id),quote_id uuid NOT NULL REFERENCES delivery_quotes(id),status order_status NOT NULL DEFAULT 'pending',subtotal integer NOT NULL,delivery_fee integer NOT NULL,total integer NOT NULL,currency text NOT NULL DEFAULT 'UGX',customer jsonb NOT NULL,delivery jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id uuid NOT NULL REFERENCES products(id),variant_id uuid REFERENCES product_variants(id),title text NOT NULL,sku text,quantity integer NOT NULL CHECK(quantity>0),unit_price integer NOT NULL,options jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL UNIQUE REFERENCES orders(id),provider text NOT NULL DEFAULT 'flutterwave',provider_reference text UNIQUE,transaction_id text,status payment_status NOT NULL DEFAULT 'pending',amount integer NOT NULL,currency text NOT NULL DEFAULT 'UGX',checkout_url text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS payment_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),provider_event_id text NOT NULL UNIQUE,payment_id uuid REFERENCES payments(id),event_type text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());

INSERT INTO fulfillment_centers(name,address,latitude,longitude) SELECT 'Kisaasi','Kisaasi, Kampala, Uganda',0.3694500,32.6027670 WHERE NOT EXISTS (SELECT 1 FROM fulfillment_centers WHERE name='Kisaasi');
INSERT INTO delivery_rate_rules(version,min_km,max_km,small_fee,medium_fee,large_fee,min_days,max_days) VALUES
('kisaasi-v1',0,10,4000,8000,17000,1,1),('kisaasi-v1',10,20,6000,9000,17500,1,2),('kisaasi-v1',20,40,8000,11000,20000,1,2),('kisaasi-v1',40,80,10000,12000,23000,2,3),('kisaasi-v1',80,150,12000,14000,26000,2,4),('kisaasi-v1',150,250,15000,18000,30000,3,4),('kisaasi-v1',250,350,18000,22000,35000,3,5),('kisaasi-v1',350,NULL,22000,27000,40000,4,7)
ON CONFLICT (version,min_km) DO NOTHING;
