import "dotenv/config";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { hash } from "bcryptjs";
import { drizzle } from "drizzle-orm/node-postgres";
import { eq, inArray } from "drizzle-orm";
import { Pool } from "pg";
import { carts, favorites, orderItems, orders, products, reviews, storefrontSettings, users } from "../src/database/schema";

type Row = { id: string; data: Record<string, any>; createTime?: string; updateTime?: string };
const status = (value: unknown): "pending" | "processing" | "shipped" | "delivered" | "cancelled" => { const normalized = String(value || "pending").toLowerCase(); return (["pending", "processing", "shipped", "delivered", "cancelled"].includes(normalized) ? normalized : "pending") as any; };

async function main() {
  const connectionString = process.env.DATABASE_URL; if (!connectionString) throw new Error("DATABASE_URL is required");
  const input = JSON.parse(await readFile(resolve(process.argv[2] || "../../.migration/firestore-export.json"), "utf8")); const source = input.collections as Record<string, Row[]>;
  const pool = new Pool({ connectionString }); const db = drizzle(pool);
  try {
    for (const row of source.users || []) { const data = row.data; const email = String(data.email || `${row.id}@firebase.invalid`).toLowerCase(); await db.insert(users).values({ firebaseUid: row.id, email, passwordHash: await hash(randomUUID(), 12), localPasswordSet: false, firstName: data.firstName || "MPWR", lastName: data.lastName || "Customer", phone: data.phone, profileImage: data.profileImage, role: data.role === "admin" ? "admin" : "customer", paymentMethods: data.paymentMethods || [], legacyData: { shippingAddresses: data.shippingAddresses || [] } }).onConflictDoUpdate({ target: users.email, set: { firebaseUid: row.id, localPasswordSet: false, firstName: data.firstName || "MPWR", lastName: data.lastName || "Customer", phone: data.phone, profileImage: data.profileImage, role: data.role === "admin" ? "admin" : "customer", paymentMethods: data.paymentMethods || [], legacyData: { shippingAddresses: data.shippingAddresses || [] }, updatedAt: new Date() } }); }
    for (const row of source.products || []) { const data = row.data; const title = String(data.title || `Product ${row.id}`); await db.insert(products).values({ legacyId: row.id, title, slug: `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}-${row.id}`, description: data.description, price: Number(data.price) || 0, imageUrl: data.image || data.imageUrl, class: data.shippingClass || "small", metadata: data }).onConflictDoUpdate({ target: products.legacyId, set: { title, description: data.description, price: Number(data.price) || 0, imageUrl: data.image || data.imageUrl, metadata: data, updatedAt: new Date() } }); }
    const accounts = await db.select({ id: users.id, firebaseUid: users.firebaseUid }).from(users); const userMap = new Map(accounts.map(user => [user.firebaseUid, user.id]));
    for (const row of source.carts || []) { const userId = userMap.get(row.id); if (userId) await db.insert(carts).values({ userId, items: row.data.items || [] }).onConflictDoUpdate({ target: carts.userId, set: { items: row.data.items || [], updatedAt: new Date() } }); }
    for (const row of source.favorites || []) { const userId = userMap.get(row.id); if (userId) await db.insert(favorites).values({ userId, items: row.data.items || [] }).onConflictDoUpdate({ target: favorites.userId, set: { items: row.data.items || [], updatedAt: new Date() } }); }
    const catalogue = await db.select({ id: products.id, legacyId: products.legacyId }).from(products); const productMap = new Map(catalogue.map(product => [product.legacyId, product.id]));
    for (const row of source.orders || []) { const data = row.data; const userId = userMap.get(data.userId); if (!userId) continue; const [existing] = await db.select({ id: orders.id }).from(orders).where(eq(orders.legacyId, row.id)).limit(1); if (existing) continue; const items = (data.items || []).filter((item: any) => productMap.has(String(item.id))); const subtotal = Number(data.subtotal) || items.reduce((sum: number, item: any) => sum + (Number(String(item.price).replace(/[^\d]/g, "")) || 0) * (Number(item.quantity) || 1), 0); const [order] = await db.insert(orders).values({ legacyId: row.id, userId, status: status(data.status), subtotal, deliveryFee: Number(data.deliveryFee) || 0, total: Number(data.total) || subtotal + (Number(data.deliveryFee) || 0), customer: data.customer || {}, delivery: { ...(data.delivery || {}), payment: data.payment || {} }, createdAt: data.createdAt ? new Date(data.createdAt) : new Date(row.createTime || Date.now()), updatedAt: data.updatedAt ? new Date(data.updatedAt) : new Date(row.updateTime || Date.now()) }).returning(); if (items.length) await db.insert(orderItems).values(items.map((item: any) => ({ orderId: order.id, productId: productMap.get(String(item.id))!, title: item.title || "Product", quantity: Number(item.quantity) || 1, unitPrice: Number(String(item.price).replace(/[^\d]/g, "")) || 0, options: { ...(item.selectedOptions || {}), legacySnapshot: item } }))); }
    for (const row of source.reviews || []) { const data = row.data; const userId = userMap.get(data.userId); const productId = productMap.get(String(data.productId)); if (!userId || !productId) continue; await db.insert(reviews).values({ legacyId: row.id, userId, productId, customerName: data.customerName || "MPWR customer", rating: Math.max(1, Math.min(5, Number(data.rating) || 1)), text: data.text || "", purchasedOptions: data.purchasedOptions || {}, attachment: data.attachment, verifiedPurchase: Boolean(data.verifiedPurchase), createdAt: data.createdAt ? new Date(data.createdAt) : new Date(row.createTime || Date.now()), updatedAt: data.updatedAt ? new Date(data.updatedAt) : new Date(row.updateTime || Date.now()) }).onConflictDoUpdate({ target: [reviews.userId, reviews.productId], set: { rating: Number(data.rating) || 1, text: data.text || "", purchasedOptions: data.purchasedOptions || {}, attachment: data.attachment, verifiedPurchase: Boolean(data.verifiedPurchase), updatedAt: new Date() } }); }
    for (const row of source.storefront || []) await db.insert(storefrontSettings).values({ key: row.id, value: row.data }).onConflictDoUpdate({ target: storefrontSettings.key, set: { value: row.data, updatedAt: new Date() } });
    console.log("Firestore import completed");
  } finally { await pool.end(); }
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
